package com.raiiiden.doomsdayfunctionality.util;

import net.minecraft.resources.ResourceLocation;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.stream.Collectors;

public class LootableBlocks {
    public static final List<ResourceLocation> LOOTABLE_BLOCK_RLS = Arrays.asList(
            new ResourceLocation("doomsdaydecoration", "atm"),
            new ResourceLocation("doomsdaydecoration", "atm_2"),
            new ResourceLocation("doomsdaydecoration", "goodsshelves"),
            new ResourceLocation("doomsdaydecoration", "goodsshelves_2"),
            new ResourceLocation("doomsdaydecoration", "goodsshelves_3"),
            new ResourceLocation("doomsdaydecoration", "goodsshelves_4"),
            new ResourceLocation("doomsdaydecoration", "goodsshelves_5"),
            new ResourceLocation("doomsdaydecoration", "goodsshelves_6"),
            new ResourceLocation("doomsdaydecoration", "apecube"),
            new ResourceLocation("doomsdaydecoration", "accessorybox_1"),
            new ResourceLocation("doomsdaydecoration", "accessorybox_2"),
            new ResourceLocation("doomsdaydecoration", "acrate_2"),
            new ResourceLocation("doomsdaydecoration", "acrate_3"),
            new ResourceLocation("doomsdaydecoration", "acrate"),
            new ResourceLocation("doomsdaydecoration", "airdrop"),
            new ResourceLocation("doomsdaydecoration", "ambulance_1"),
            new ResourceLocation("doomsdaydecoration", "ambulance_2"),
            new ResourceLocation("doomsdaydecoration", "ambulance_3"),
            new ResourceLocation("doomsdaydecoration", "ammunitionbox"),
            new ResourceLocation("doomsdaydecoration", "arcadegame_2"),
            new ResourceLocation("doomsdaydecoration", "arcadegame_3"),
            new ResourceLocation("doomsdaydecoration", "arcadegame_4"),
            new ResourceLocation("doomsdaydecoration", "arcadegame_5"),
            new ResourceLocation("doomsdaydecoration", "arcadegame"),
            new ResourceLocation("doomsdaydecoration", "barrel"),
            new ResourceLocation("doomsdaydecoration", "bathtub"),
            new ResourceLocation("doomsdaydecoration", "beaker"),
            new ResourceLocation("doomsdaydecoration", "black_jeep_1"),
            new ResourceLocation("doomsdaydecoration", "black_jeep_2"),
            new ResourceLocation("doomsdaydecoration", "blackluggage"),
            new ResourceLocation("doomsdaydecoration", "blackpickuptruck"),
            new ResourceLocation("doomsdaydecoration", "blackstationwagon"),
            new ResourceLocation("doomsdaydecoration", "blackvan_1"),
            new ResourceLocation("doomsdaydecoration", "blackvan_2"),
            new ResourceLocation("doomsdaydecoration", "blueluggage"),
            new ResourceLocation("doomsdaydecoration", "blue_jeep_1"),
            new ResourceLocation("doomsdaydecoration", "blue_jeep_2"),
            new ResourceLocation("doomsdaydecoration", "bluepickuptruck"),
            new ResourceLocation("doomsdaydecoration", "bluestationwagon"),
            new ResourceLocation("doomsdaydecoration", "bluevan_1"),
            new ResourceLocation("doomsdaydecoration", "bluevan_2"),
            new ResourceLocation("doomsdaydecoration", "bodybag"),
            new ResourceLocation("doomsdaydecoration", "book"),
            new ResourceLocation("doomsdaydecoration", "bookpile_2"),
            new ResourceLocation("doomsdaydecoration", "bookpile"),
            new ResourceLocation("doomsdaydecoration", "bottle_2"),
            new ResourceLocation("doomsdaydecoration", "bottle"),
            new ResourceLocation("doomsdaydecoration", "brown_jeep_1"),
            new ResourceLocation("doomsdaydecoration", "brown_jeep_2"),
            new ResourceLocation("doomsdaydecoration", "browning_m2"),
            new ResourceLocation("doomsdaydecoration", "brownpickuptruck"),
            new ResourceLocation("doomsdaydecoration", "bucket"),
            new ResourceLocation("doomsdaydecoration", "cabinet_2"),
            new ResourceLocation("doomsdaydecoration", "cabinet_3"),
            new ResourceLocation("doomsdaydecoration", "cabinet"),
            new ResourceLocation("doomsdaydecoration", "cart_2"),
            new ResourceLocation("doomsdaydecoration", "cart"),
            new ResourceLocation("doomsdaydecoration", "carton_2"),
            new ResourceLocation("doomsdaydecoration", "carton_3"),
            new ResourceLocation("doomsdaydecoration", "carton"),
            new ResourceLocation("doomsdaydecoration", "cashregister"),
            new ResourceLocation("doomsdaydecoration", "centrifuge"),
            new ResourceLocation("doomsdaydecoration", "chalk"),
            new ResourceLocation("doomsdaydecoration", "chemicalprotectiveclothing_2"),
            new ResourceLocation("doomsdaydecoration", "chemicalprotectiveclothing"),
            new ResourceLocation("doomsdaydecoration", "classroomdesk"),
            new ResourceLocation("doomsdaydecoration", "closestool"),
            new ResourceLocation("doomsdaydecoration", "coffee"),
            new ResourceLocation("doomsdaydecoration", "coffeemachine"),
            new ResourceLocation("doomsdaydecoration", "constanttemperatureincubator"),
            new ResourceLocation("doomsdaydecoration", "cup_2"),
            new ResourceLocation("doomsdaydecoration", "cup"),
            new ResourceLocation("doomsdaydecoration", "desk_2"),
            new ResourceLocation("doomsdaydecoration", "desk_3"),
            new ResourceLocation("doomsdaydecoration", "desk"),
            new ResourceLocation("doomsdaydecoration", "discard_white_jeep_1"),
            new ResourceLocation("doomsdaydecoration", "discard_white_jeep_2"),
            new ResourceLocation("doomsdaydecoration", "discardblackcar_1"),
            new ResourceLocation("doomsdaydecoration", "discardblackcar_2"),
            new ResourceLocation("doomsdaydecoration", "discardblackjeep_1"),
            new ResourceLocation("doomsdaydecoration", "discardblackjeep_2"),
            new ResourceLocation("doomsdaydecoration", "discardblackpickuptruck"),
            new ResourceLocation("doomsdaydecoration", "discardblackstationwagon"),
            new ResourceLocation("doomsdaydecoration", "discardbluecar_1"),
            new ResourceLocation("doomsdaydecoration", "discardbluecar_2"),
            new ResourceLocation("doomsdaydecoration", "discardbluejeep_1"),
            new ResourceLocation("doomsdaydecoration", "discardbluejeep_2"),
            new ResourceLocation("doomsdaydecoration", "discardbluepickuptruck"),
            new ResourceLocation("doomsdaydecoration", "discardbluestationwagon"),
            new ResourceLocation("doomsdaydecoration", "discardbrownjeep_1"),
            new ResourceLocation("doomsdaydecoration", "discardbrownjeep_2"),
            new ResourceLocation("doomsdaydecoration", "discardbrownpickuptruck"),
            new ResourceLocation("doomsdaydecoration", "discardgreencar_1"),
            new ResourceLocation("doomsdaydecoration", "discardgreencar_2"),
            new ResourceLocation("doomsdaydecoration", "discardgreenjeep_1"),
            new ResourceLocation("doomsdaydecoration", "discardgreenjeep_2"),
            new ResourceLocation("doomsdaydecoration", "discardgreenpickuptruck"),
            new ResourceLocation("doomsdaydecoration", "discardgreenstationwagon"),
            new ResourceLocation("doomsdaydecoration", "discardgreycar_1"),
            new ResourceLocation("doomsdaydecoration", "discardgreycar_2"),
            new ResourceLocation("doomsdaydecoration", "discardgreyjeep_1"),
            new ResourceLocation("doomsdaydecoration", "discardgreyjeep_2"),
            new ResourceLocation("doomsdaydecoration", "discardgreypickuptruck"),
            new ResourceLocation("doomsdaydecoration", "discardgreystationwagon"),
            new ResourceLocation("doomsdaydecoration", "discardkhakicar_1"),
            new ResourceLocation("doomsdaydecoration", "discardkhakicar_2"),
            new ResourceLocation("doomsdaydecoration", "discardkhakistationwagon"),
            new ResourceLocation("doomsdaydecoration", "discardpolicecar_1"),
            new ResourceLocation("doomsdaydecoration", "discardpolicecar_2"),
            new ResourceLocation("doomsdaydecoration", "discardpolicecar_3"),
            new ResourceLocation("doomsdaydecoration", "discardpolicecar_4"),
            new ResourceLocation("doomsdaydecoration", "discardredcar_1"),
            new ResourceLocation("doomsdaydecoration", "discardredcar_2"),
            new ResourceLocation("doomsdaydecoration", "discardredjeep_1"),
            new ResourceLocation("doomsdaydecoration", "discardredjeep_2"),
            new ResourceLocation("doomsdaydecoration", "discardredpickuptruck"),
            new ResourceLocation("doomsdaydecoration", "discardredstationwagon"),
            new ResourceLocation("doomsdaydecoration", "discardwhitecar_1"),
            new ResourceLocation("doomsdaydecoration", "discardwhitecar_2"),
            new ResourceLocation("doomsdaydecoration", "discardwhitepickuptruck"),
            new ResourceLocation("doomsdaydecoration", "discardwhitestationwagon"),
            new ResourceLocation("doomsdaydecoration", "dolly"),
            new ResourceLocation("doomsdaydecoration", "draw_2"),
            new ResourceLocation("doomsdaydecoration", "draw_3"),
            new ResourceLocation("doomsdaydecoration", "draw_4"),
            new ResourceLocation("doomsdaydecoration", "draw_5"),
            new ResourceLocation("doomsdaydecoration", "draw"),
            new ResourceLocation("doomsdaydecoration", "drug"),
            new ResourceLocation("doomsdaydecoration", "electricoven"),
            new ResourceLocation("doomsdaydecoration", "emptytesttuberack"),
            new ResourceLocation("doomsdaydecoration", "firstaidkit"),
            new ResourceLocation("doomsdaydecoration", "foodstand_1"),
            new ResourceLocation("doomsdaydecoration", "foodstand_2"),
            new ResourceLocation("doomsdaydecoration", "foodstand_3"),
            new ResourceLocation("doomsdaydecoration", "forklifttruck"),
            new ResourceLocation("doomsdaydecoration", "freezer"),
            new ResourceLocation("doomsdaydecoration", "fridge_2"),
            new ResourceLocation("doomsdaydecoration", "fridge"),
            new ResourceLocation("doomsdaydecoration", "front_blue_sedan"),
            new ResourceLocation("doomsdaydecoration", "frontblacksedan"),
            new ResourceLocation("doomsdaydecoration", "frontgraysedan"),
            new ResourceLocation("doomsdaydecoration", "frontgreensedan"),
            new ResourceLocation("doomsdaydecoration", "frontkhakisedan"),
            new ResourceLocation("doomsdaydecoration", "frontredsedan"),
            new ResourceLocation("doomsdaydecoration", "frontwhitesedan"),
            new ResourceLocation("doomsdaydecoration", "gasstation"),
            new ResourceLocation("doomsdaydecoration", "gastank"),
            new ResourceLocation("doomsdaydecoration", "generator"),
            new ResourceLocation("doomsdaydecoration", "fixedgenerator"),
            new ResourceLocation("doomsdaydecoration", "glassware"),
            new ResourceLocation("doomsdaydecoration", "grill"),
            new ResourceLocation("doomsdaydecoration", "green_hummer_1"),
            new ResourceLocation("doomsdaydecoration", "green_hummer_2"),
            new ResourceLocation("doomsdaydecoration", "green_hummer_3"),
            new ResourceLocation("doomsdaydecoration", "green_hummer_4"),
            new ResourceLocation("doomsdaydecoration", "green_hummer_5"),
            new ResourceLocation("doomsdaydecoration", "green_hummer_6"),
            new ResourceLocation("doomsdaydecoration", "green_hummer_7"),
            new ResourceLocation("doomsdaydecoration", "green_hummer_8"),
            new ResourceLocation("doomsdaydecoration", "green_hummer_9"),
            new ResourceLocation("doomsdaydecoration", "green_jeep_1"),
            new ResourceLocation("doomsdaydecoration", "green_jeep_2"),
            new ResourceLocation("doomsdaydecoration", "greenluggage"),
            new ResourceLocation("doomsdaydecoration", "greenpickuptruck"),
            new ResourceLocation("doomsdaydecoration", "greentravelcar"),
            new ResourceLocation("doomsdaydecoration", "greenvan_1"),
            new ResourceLocation("doomsdaydecoration", "greenvan_2"),
            new ResourceLocation("doomsdaydecoration", "grey_jeep_1"),
            new ResourceLocation("doomsdaydecoration", "grey_jeep_2"),
            new ResourceLocation("doomsdaydecoration", "greyluggage"),
            new ResourceLocation("doomsdaydecoration", "greypickuptruck"),
            new ResourceLocation("doomsdaydecoration", "greyvan_1"),
            new ResourceLocation("doomsdaydecoration", "greyvan_2"),
            new ResourceLocation("doomsdaydecoration", "greywagon"),
            new ResourceLocation("doomsdaydecoration", "hangingclothes"),
            new ResourceLocation("doomsdaydecoration", "host_2"),
            new ResourceLocation("doomsdaydecoration", "host"),
            new ResourceLocation("doomsdaydecoration", "indoorgarbagebin"),
            new ResourceLocation("doomsdaydecoration", "insulationcabinet"),
            new ResourceLocation("doomsdaydecoration", "jar"),
            new ResourceLocation("doomsdaydecoration", "kettle"),
            new ResourceLocation("doomsdaydecoration", "khaki_hummer_1"),
            new ResourceLocation("doomsdaydecoration", "khaki_hummer_2"),
            new ResourceLocation("doomsdaydecoration", "khaki_hummer_3"),
            new ResourceLocation("doomsdaydecoration", "khaki_hummer_4"),
            new ResourceLocation("doomsdaydecoration", "khaki_hummer_5"),
            new ResourceLocation("doomsdaydecoration", "khaki_hummer_6"),
            new ResourceLocation("doomsdaydecoration", "khaki_hummer_7"),
            new ResourceLocation("doomsdaydecoration", "khaki_hummer_8"),
            new ResourceLocation("doomsdaydecoration", "khaki_hummer_9"),
            new ResourceLocation("doomsdaydecoration", "khakiluggage"),
            new ResourceLocation("doomsdaydecoration", "khakistationwagon"),
            new ResourceLocation("doomsdaydecoration", "knapsack"),
            new ResourceLocation("doomsdaydecoration", "rearwhitesedan"),
            new ResourceLocation("doomsdaydecoration", "rearredsedan"),
            new ResourceLocation("doomsdaydecoration", "rearkhakisedan"),
            new ResourceLocation("doomsdaydecoration", "rearblacksedan"),
            new ResourceLocation("doomsdaydecoration", "rear_blue_sedan"),
            new ResourceLocation("doomsdaydecoration", "reargreensedan"),
            new ResourceLocation("doomsdaydecoration", "reargraysedan"),
            new ResourceLocation("doomsdaydecoration", "shopping_cart"),
            new ResourceLocation("doomsdaydecoration", "remains101010"),
            new ResourceLocation("doomsdaydecoration", "remains1010"),
            new ResourceLocation("doomsdaydecoration", "remains10"),
            new ResourceLocation("doomsdaydecoration", "remains111"),
            new ResourceLocation("doomsdaydecoration", "remains11"),
            new ResourceLocation("doomsdaydecoration", "remains1"),
            new ResourceLocation("doomsdaydecoration", "remains222"),
            new ResourceLocation("doomsdaydecoration", "remains22"),
            new ResourceLocation("doomsdaydecoration", "remains2"),
            new ResourceLocation("doomsdaydecoration", "remains333"),
            new ResourceLocation("doomsdaydecoration", "remains33"),
            new ResourceLocation("doomsdaydecoration", "remains3"),
            new ResourceLocation("doomsdaydecoration", "remains444"),
            new ResourceLocation("doomsdaydecoration", "remains44"),
            new ResourceLocation("doomsdaydecoration", "remains4"),
            new ResourceLocation("doomsdaydecoration", "remains555"),
            new ResourceLocation("doomsdaydecoration", "remains55"),
            new ResourceLocation("doomsdaydecoration", "remains5"),
            new ResourceLocation("doomsdaydecoration", "remains666"),
            new ResourceLocation("doomsdaydecoration", "remains66"),
            new ResourceLocation("doomsdaydecoration", "remains6"),
            new ResourceLocation("doomsdaydecoration", "remains777"),
            new ResourceLocation("doomsdaydecoration", "remains77"),
            new ResourceLocation("doomsdaydecoration", "remains7"),
            new ResourceLocation("doomsdaydecoration", "remains888"),
            new ResourceLocation("doomsdaydecoration", "remains88"),
            new ResourceLocation("doomsdaydecoration", "remains8"),
            new ResourceLocation("doomsdaydecoration", "remains999"),
            new ResourceLocation("doomsdaydecoration", "remains99"),
            new ResourceLocation("doomsdaydecoration", "remains9"),
            new ResourceLocation("doomsdaydecoration", "vendingmachine"),
            new ResourceLocation("doomsdaydecoration", "vendingmachine_2"),
            new ResourceLocation("doomsdaydecoration", "vendingmachine_3"),
            new ResourceLocation("doomsdaydecoration", "vendingmachine_4")
            );

    private static final Map<String, String> CLASS_TO_REGISTRY_NAME_MAP = new HashMap<>();

    public static String[] getMixinTargets() {
        return LOOTABLE_BLOCK_RLS.stream()
                .map(rl -> {
                    String registryPath = rl.getPath();
                    String convertedClassName = toPascalCase(registryPath);

                    String finalClassName = CLASS_TO_REGISTRY_NAME_MAP.entrySet().stream()
                            .filter(entry -> entry.getValue().equals(registryPath))
                            .map(Map.Entry::getKey)
                            .findFirst()
                            .orElse(convertedClassName);

                    return "net.mcreator.doomsdaydecoration.block." + finalClassName + "Block";
                })
                .toArray(String[]::new);
    }

    private static String toPascalCase(String snakeCase) {
        StringBuilder pascalCase = new StringBuilder();
        boolean capitalizeNext = true;
        for (char c : snakeCase.toCharArray()) {
            if (c == '_') {
                capitalizeNext = true;
            } else {
                if (capitalizeNext) {
                    pascalCase.append(Character.toUpperCase(c));
                    capitalizeNext = false;
                } else {
                    pascalCase.append(c);
                }
            }
        }
        return pascalCase.toString();
    }
}